PROFILE = {
    "name": "Priya Nair",
    "email": "priya.nair@example.com",
    "phone": "+44 7911 123456",
    "profession": "nurse",
    "role": "Registered Nurse",
    "experience_years": 4,
    "experience_min": 2,
    "experience_max": 8,
    "location": "London, UK",
    "country": "United Kingdom",
    "timezone": "Europe/London",
    "currency": "GBP",
    "min_salary": 30000,
    "linkedin": "https://www.linkedin.com/in/priyanair",
    "portfolio": "",
    "website": "",
    "skills": {
        "clinical": ["Patient Assessment", "IV Therapy", "Wound Care", "Medication Administration"],
        "patient_care": ["Bedside Care", "Patient Education", "Care Planning", "Vital Signs Monitoring"],
        "specialties": ["Emergency Care", "ICU", "Pediatric Nursing"],
        "documentation": ["Electronic Health Records", "Care Documentation", "Clinical Handover"],
        "certifications": ["BLS", "ACLS", "NMC Registered"],
    },
    "projects": [
        {
            "name": "Emergency Department Quality Initiative",
            "description": "led a triage workflow redesign that cut average wait times by 25%",
            "tech": ["Triage Protocols", "Team Coordination", "Process Improvement"],
        },
    ],
    "experience": [
        {
            "id": 1,
            "role": "Registered Nurse",
            "company": "St. Mary's Hospital",
            "location": "London, UK",
            "duration": "Mar 2022 - Present",
            "type": "full-time",
            "highlights": [
                "Manage a 6-bed acute care unit with 20+ patients per shift",
                "Mentor newly qualified nurses and student placements",
                "Reduced medication errors by introducing a double-check protocol",
            ],
            "tech": ["Emergency Care", "EHR Systems", "Team Leadership"],
        },
    ],
    "education": "BSc (Hons) Nursing - King's College London (2018-2021)",
    "languages": ["English", "Malayalam"],
    "looking_for": [
        "Registered Nurse",
        "Staff Nurse",
        "ICU Nurse",
        "Emergency Nurse",
    ],
    "excluded_roles": [],
    "excluded_locations": [],
    "prefers_remote": False,
}
