from apps.jobs.services.core import (
    SALARY_PATTERNS,
    _SALARY_NEGATIVE,
    _format_salary,
    _extract_salary_from_text,
    job_exists,
    save_job,
    bulk_save_jobs,
    save_application,
    save_web_apply,
    update_daily_stats,
    get_recent_jobs,
    get_matched_jobs,
    get_all_applications,
    get_job_stats,
    is_company_email,
    _extract_emails_from_text,
    _get_http_client,
    find_job_salary,
    _fetch_salary_for_job,
    enrich_jobs_with_salaries,
    find_job_email,
    _fetch_email_for_job,
    enrich_jobs_with_emails,
)

from apps.jobs.services.cv_engine_client import (
    generate_cv,
    get_ats_score,
    enrich_company,
    enrich_company_with_ai,
    CVEngineUnavailableError,
)
